<?php
require_once __DIR__.'/../includes/auth.php'; requireRole(['CUSTOMER']);
$userId=$_SESSION['user_id']; $client=null; $projects=[];
if(tableExists($pdo,'clients')){
 if(hasColumn($pdo,'clients','user_id')){$s=$pdo->prepare('SELECT * FROM clients WHERE user_id=? LIMIT 1');$s->execute([$userId]);$client=$s->fetch();}
 if(!$client && hasColumn($pdo,'clients','email')){$s=$pdo->prepare('SELECT * FROM clients WHERE email=? LIMIT 1');$s->execute([$_SESSION['email']]);$client=$s->fetch();}
}
$clientId=$client['client_id']??$client['id']??null;
if($clientId && tableExists($pdo,'projects') && hasColumn($pdo,'projects','client_id')){$pk=firstExistingColumn($pdo,'projects',['project_id','id']);$s=$pdo->prepare('SELECT * FROM projects WHERE client_id=? ORDER BY '.(firstExistingColumn($pdo,'projects',['created_at','project_id','id']) ?? 'client_id').' DESC');$s->execute([$clientId]);$projects=$s->fetchAll();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Projects | VANTAGE</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><div class="app"><?php include __DIR__.'/../includes/sidebar.php'; ?><main class="main"><header class="topbar"><div><div class="eyebrow">CUSTOMER PORTAL</div><h2>My Projects</h2><p>Track the work VANTAGE is delivering for you.</p></div></header><section class="dashboard"><div class="project-grid"><?php if($projects): foreach($projects as $p): $progress=max(0,min(100,(int)($p['progress']??$p['completion_percent']??0))); ?><article class="project-card"><div class="project-status"><?= htmlspecialchars($p['status']??'ACTIVE') ?></div><h3><?= htmlspecialchars($p['project_name']??$p['name']??'Project') ?></h3><p><?= htmlspecialchars($p['description']??'No description available.') ?></p><div class="progress-container"><div class="progress-bar" style="width:<?= $progress ?>%"></div></div><div class="project-progress"><?= $progress ?>% complete</div><a class="btn secondary-dark" href="project.php?id=<?= urlencode((string)($p['project_id']??$p['id']??'')) ?>">View details</a></article><?php endforeach; else: ?><div class="panel empty"><h3>No projects yet.</h3><p>Your project will appear here once the VANTAGE team links it to your customer account.</p></div><?php endif; ?></div></section></main></div></body></html>
